### ISSUE TITLE
Spanish translation to date

### ISSUE THREAD

**Issue by cubiczx** [jbub/django-suit-locale#5]
The date in admin of django-suite with django-suite-locale show "Lunes, 7th Septiembre 2015" and the "th" is incorrect in spanish the correct is "de" "Lunes, 7 de Septiembre de 2015".
The string to translate are not present in [Transifex](https://www.transifex.com/jbub/django-suit-locale/viewstrings/#es/djangopo/20475635)

**Comment by jbub** [comment]
Hello, thanks for the report, it would be really helpful if you could link the missing string in the django admin template (or python code). Feel free to look here: https://github.com/django/django/tree/master/django/contrib/admin

**Comment by cubiczx** [comment]
Suppose that comes from Python strftime or datetime function.

**Comment by cubiczx** [comment]
I change settings.py:

``` python
# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.
USE_L10N = False
DATE_FORMAT = 'd-m-Y'
DATETIME_FORMAT = 'd-m-Y H:i'
```

But date time not change

**Comment by jbub** [comment]
Does this happen in some specific place of django admin (suit) or does it affect the whole admin ?

**Comment by cubiczx** [comment]
I say what's in top bar of /admin page

**Comment by cubiczx** [comment]
I see in django-suite code /suit/templates/admin/base.html:

``` python
{% block header_time %}
            <div class="header-content header-content-first">
              <div class="header-column icon">
                <i class="icon-time"></i>
              </div>
              <div class="header-column">
                <span class="date"> {% suit_date %}</span><br>
                <span class="time" id="clock">{% suit_time %}</span>
              </div>
            </div>
            {% endblock %}
```

I will change {% suit_date %} format

I see in /suit/templates/templatetags/suite_tags.py:

``` python
@register.tag
def suit_date(parser, token):
    return NowNode(get_config('HEADER_DATE_FORMAT'))
```

Use a HEADER_DATE_FORMAT of suite default config of /suit/config.py: 

``` python
def default_config():
    return {
        'VERSION': VERSION,

        # configurable
        'ADMIN_NAME': 'Django Suit',
        'HEADER_DATE_FORMAT': 'l, jS F Y',
```

I change in my settings.py:

``` python
SUIT_CONFIG = {
'HEADER_DATE_FORMAT': 'l j \d\e F \d\e Y',
}
```
